#! /bin/bash
# Copyright (c) 2023 Hunan OpenValley Digital Industry Development Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE_KHZG file.
#
#编译依赖
#sudo apt install g++-multilib git python3 curl

python3 ./src/flutter/attachment/scripts/ohos.py "$@"
