name: 报告 Bug
description: |
  在 Flutter 中发现导致应用崩溃或抛出异常的 Bug，
  某个组件有缺陷，或界面显示异常。
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        感谢使用 Flutter！

        如需帮助，请查阅文档或在 Stack Overflow 上提问：

          - https://flutter.dev/
          - https://api.flutter.dev/
          - https://stackoverflow.com/questions/tagged/flutter?sort=frequent
  - type: markdown
    attributes:
      value: |
        填写表单前，请确认以下事项：
        - 已搜索[已有的 Issue](https://gitcode.com/CPF-Flutter/flutter_flutter/issues)
        - 已阅读[提交 Bug 指南](https://docs.flutter.dev/resources/bug-reports)
  - type: textarea
    attributes:
      label: 复现步骤
      description: 请详细描述如何复现你遇到的问题。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期望结果
      description: 请描述期望发生的行为。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请描述实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 代码示例
      description: |
        请创建一个最小可复现示例来展示问题，并在下方代码块中粘贴。

        可使用 `flutter create bug` 命令创建项目并修改 `main.dart` 文件。

        也可以使用 https://dartpad.dev/ 或创建公开的 GitCode 仓库来分享示例。

        缺少此示例将很难推进问题排查，我们可能不得不关闭此 Issue。

        注意：请勿上传文本截图，请使用代码块或上述方式提供代码。
      value: |
        <details open><summary>代码示例</summary>

        ```dart
        [在此粘贴代码]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频
      description: |
        如有，请上传 Bug 相关的截图或视频。
      value: |
        <details open>
        <summary>截图 / 视频演示</summary>

        [在此上传媒体文件]

        </details>
  - type: textarea
    attributes:
      label: 日志
      description: |
        请在下方代码块中粘贴所运行命令的完整日志。如果运行了 `flutter` 命令，请附上添加 `--verbose` 参数后的输出，例如 `flutter --verbose create foo` 的输出。

        如果日志过大无法上传到 GitCode，可以将其保存为 `txt` 文件，或使用 https://pastebin.com 等在线工具分享。

        注意：请勿上传文本截图，请使用代码块或上述方式提供日志。
      value: |
        <details open><summary>日志</summary>

        ```console
        [在此粘贴日志]
        ```

        </details>
  - type: textarea
    attributes:
      label: Flutter Doctor 输出
      description: |
        请提供 `flutter doctor -v` 的完整输出
      value: |
        <details open><summary>Doctor 输出</summary>

        ```console
        [在此粘贴输出]
        ```

        </details>
    validations:
      required: true
