name: 应用存在内存、功耗或包体积问题
description: |
  开发应用时发现内存占用过高、功耗过大（如 CPU/GPU 使用率过高），
  或应用体积过大。
labels: ['performance', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        感谢使用 Flutter！

        如需帮助，请查阅文档或在 Stack Overflow 上提问：

          - https://flutter.dev/
          - https://api.flutter.dev/
          - https://stackoverflow.com/questions/tagged/flutter?sort=frequent
  - type: textarea
    attributes:
      label: 复现步骤
      description: 请详细描述如何复现你遇到的问题，以及如何测量性能。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 代码示例
      description: |
        请创建一个最小可复现示例来展示问题，并在下方代码块中粘贴。

        请尝试在测试应用中复现问题：运行 `flutter create janktest` 并在其中重现你遇到的情况，或克隆你的应用并逐步删减代码，直到卡顿问题可以通过单个 `.dart` 文件复现。

        如果仅靠 `.dart` 文件无法复现（例如需要资源文件或插件），请创建 GitCode 仓库并上传代码。

        缺少此示例将很难推进问题排查，我们可能不得不关闭此 Issue。

        注意：请勿上传文本截图，请使用代码块或上述方式提供代码。
      value: |
        <details open><summary>代码示例</summary>

        ```dart
        [在此粘贴代码]
        ```

        </details>
    validations:
      required: true
  - type: dropdown
    id: target_platforms
    attributes:
      label: 在哪些目标平台上出现了此问题？
      multiple: true
      options:
        - OHOS
        - Android
        - iOS
        - Web
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: textarea
    attributes:
      label: 操作系统/浏览器名称及版本 | 设备信息
      description: |
        测试系统运行的目标操作系统版本是什么？Web 平台请提供浏览器版本。
        请同时提供设备信息（型号、CPU 架构等）。
    validations:
      required: true
  - type: dropdown
    id: device-kind
    attributes:
      label: 该问题在模拟器和真机上都会出现吗？
      options:
        - "不确定"
        - "是"
        - "否"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 日志
      description: |
        请在下方代码块中粘贴所运行命令的完整日志。如果运行了 `flutter` 命令，请附上添加 `--verbose` 参数后的输出，例如 `flutter --verbose create foo` 的输出。

        如果日志过大无法上传到 GitCode，可以将其保存为 `txt` 文件，或使用 https://pastebin.com 等在线工具分享。

        注意：请勿上传文本截图，请使用代码块或上述方式提供日志。
      value: |
        <details open><summary>日志</summary>

        ```console
        [在此粘贴日志]
        ```

        </details>
  - type: textarea
    attributes:
      label: Flutter Doctor 输出
      description: |
        最后，请在连接设备的情况下粘贴 `flutter doctor -v` 的输出。
      value: |
        <details open><summary>Doctor 输出</summary>

        ```console
        [在此粘贴输出]
        ```

        </details>
    validations:
      required: true
