name: 创建功能追踪 Issue
description: 作为贡献者，创建一个功能追踪 Issue，用于跟踪某项大型功能及其子任务的进展。
labels: ['triage', 'feature-tracking']
title: '☂️ <功能标题>'
projects: ["flutter/82"]
body:
  - type: input
    id: design_doc
    attributes:
      label: 设计文档
      description: 如有，请附上此功能的设计文档链接。
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 请描述你要添加的功能。
    validations:
      required: true
  - type: textarea
    id: tracking_issues
    attributes:
      label: 跟踪 Issue
      description: 与此功能关联的 Issue 列表。
    validations:
      required: true
